---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
  labels:
    app: "database_operations"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 12h
  url: https://helm.mariadb.com/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "25.8.3"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 12h
  targetNamespace: mariadb
  values:

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: "25.8.3"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 12h
  targetNamespace: mariadb
  values:
    crds:
      enabled: true
    image:
      repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
      pullPolicy: IfNotPresent
      tag: ""
    logLevel: INFO
    clusterName: cluster.local
    currentNamespaceOnly: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 15s
        scrapeTimeout: 25s
    resources: {}
    # requests:
    #   cpu: 10m
    #   memory: 32Mi

    certController:
      enabled: true
      image:
        repository: docker-registry3.mariadb.com/mariadb-operator/mariadb-operator
        pullPolicy: IfNotPresent
        tag: ""
      serviceMonitor:
        enabled: true
    config:
      galeraLibPath: /usr/lib/galera/libgalera_smm.so
      mariadbDefaultVersion: "11.8"
      mariadbImage: docker-registry1.mariadb.com/library/mariadb:11.8.2
      maxscaleImage: docker-registry2.mariadb.com/mariadb/maxscale:23.08.5
      exporterImage: prom/mysqld-exporter:v0.15.1
      exporterMaxscaleImage: docker-registry2.mariadb.com/mariadb/maxscale-prometheus-exporter-ubi:v0.0.1

