---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    pod-security.kubernetes.io/enforce = "privileged"
    app = "external-secrets"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      version: 0.19.2

  interval: 1m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  values:
    global:
      nodeSelector:
        node: "worker"
    log:
      level: info
      timeEncoding: epoch
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
    grafanaDashboard:
      enabled: true
    replicaCount: 1
    revisionHistoryLimit: 15
