apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:h34ClTBsV/c41KhxHlfX/YsXv9JmP0QHmJlbgQ==,iv:gHIMAvVHqiIH61XdcdYfrhmfrz3qxHqJu068y7IoBtE=,tag:oFXoM0FeqZS5c9Ljt/u7RA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:UNaL4TPyHVXg1bBVCD+6l+9aYVwjrzbpHoyc4OBnrvnQPvTUTWq8hB6HANu6MNUYw6f/OT8CeGY=,iv:3TS7p122z8poed/IgdQk7IuypcLU3Ek/Lmj6Cby+8BM=,tag:vO6yuN7iUUh8IuGJzON1EQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: awssm-secret
    namespace: external-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNmU2cXY3WkpQYUdERlpN
            ekFqMU85S1pjODltL29Nb3BlTzNuWVhmTEdFClZ0bWlDVXZDMzY4MDhTd05SMW9P
            TEFSNXhGRlpuYlhHRSs2Nis4Q2FzWFkKLS0tICs0VWs2SXFSRXBGakpFK0NYYzMw
            NWZ4cWkyVi83cXp1cXZkWDEwS3h4TWcKnoN2aP1Uakgx3coXA/he5d7zEXUJhoaa
            wp6emBraZQQWlzCdoicoJb5s9gZ4S75RK/kkUnxPvL0nQdx9gBhxNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T22:03:17Z"
    mac: ENC[AES256_GCM,data:xNPhg96yLLwmDgwIYRmiijI2T9vRtiJDv9RU818WF+BHy7XmYHiYQwseCH7wgPzXPdzkP16C3DpxmSYLJrxz31t0bQTrAmNxomK+blAcwRGvmnABxk3TfWqUF99YzAU156ib0T9feYkjGc5fIwm8HoAIFFiyK0NcEaD9MMFvmGk=,iv:OfTy4kuBFea89egyBp/LPiBHq0sVtoGU3LDRyq/aCW8=,tag:pldZe1B1s9j7ASH7IfCr7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
