---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-iscsi
  namespace: flux-system
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  targetNamespace: storage
  values:
    csiDriver:
      name: "iscsi"
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 192.168.20.106
          port: 443
          allowInsecure: true
          apiKey: ${TRUENAS_API_KEY}
          apiVersion: 2
        zfs:
          datasetParentName: home-share/iscsi/k8s/dev/volumes
          detachedSnapshotsDatasetParentName: home-share/iscsi/k8s/dev/snapshots
          zvolCompression: "on"
          zvolDedup:
          zvolEnableReservation: false
          zvolBlocksize:
        iscsi:
          targetPortal: "192.168.20.106:3260"
          interface:
          namePrefix: csi-
          nameSuffix: "-k8sdev"
          targetGroups:
            - targetGroupPortalGroup: 11
              targetGroupInitiatorGroup: 21
              targetGroupAuthType: None
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: "SSD"
          extentAvailThreshold: 0
