---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-crds
  namespace: flux-system
spec:
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg-crds
      version: "1.28.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg-crds
        namespace: flux-system
      interval: 12h
  targetNamespace: database
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.27.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
      interval: 12h
  targetNamespace: database
  values:
    replicaCount: 2
    crds:
      create: true
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: false
        namespace: "monitoring"
    nodeSelector:
      node: "worker"
