---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: silverbullet
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./apps/dev/silverbullet
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: silverbullet
      namespace: silverbullet
  dependsOn:
    - name: controllers
    - name: components
