---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-smb
      version: v1.17.0
      sourceRef:
        name: csi-driver-smb
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  targetNamespace: storage
  values:
    windows:
      enabled: false
