---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: smb-exception
  namespace: storage
spec:
  exceptions:
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - DaemonSet
        namespaces:
        - storage
  conditions:
    any:
    - key: "{{ request.object.metadata.labels.app || '' }}"
      operator: Equals
      value: smb
