---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.18.2
  interval: 1h
  targetNamespace: cert-manager
  values:
    crds:
      enabled: true
      keep: true
    serviceAccount:
      create: true
      automountServiceAccountToken: true
    enableCertificateOwnerRef: true
    webhook:
      replicaCount: 2
      timeoutSeconds: 30
    dns01RecursiveNameservers: "1.1.1.1:53,9.9.9.9:53"
    dns01RecursiveNameserversOnly: true
    approveSignerNames:
      - issuers.cert-manager.io/*
      - clusterissuers.cert-manager.io/*
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
    podDnsPolicy: None
