---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-crds
  namespace: flux-system
spec:
  interval: 24h
  url: https://wiremind.github.io/wiremind-helm-charts
---


