apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    statusStyle: dot
    theme: dark
    color: stone
    headerStyle: boxedWidgets
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/alexrf45
  services.yaml: |
    - Monitoring:
        - Grafana (PROD):
            href: https://prod-grafana.bun-dominant.ts.net
            description: Grafana
    - Apps:
        - IT-Tools (PROD):
            href: https://https://prod-it-tools.bun-dominant.ts.net
            description: IT-Tools

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        text_size: md
        locale: us
        format:
          hour12: false
          timeStyle: long
          dateStyle: long
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
