---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freenas-csi
  namespace: storage
spec:
  interval: 30m
  path: ./controllers/base/freenas-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system  # or whatever your git repo source is named
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: truenas-config
      - kind: Secret
        name: truenas-credentials
