apiVersion: v1
kind: Secret
metadata:
    name: truenas-credentials
    namespace: flux-system
type: Opaque
stringData:
    TRUENAS_PASSWORD: ENC[AES256_GCM,data:H1kVEbO/U3zoZfDsVW8HneAhK6dmSyC5,iv:bGbPUGY+Vd9x2Ej8jY/47GkojCqTs2vw5bxCnVEuSDE=,tag:VdfUnLmnzHxSTQelOpBbJg==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:dnN39iiUlhnxMT1GPNI7GRKTeXwV5x1d4Z381WRp4QnGFV77ED8zsGRXIuFPFyOI7in5rVSht7p0D2mrJA831xut,iv:mch9ZHE1UIY5qxC4KA7PB7zkF9FHYrcFS7l83fNZlJk=,tag:lOjMZaZhv/i4ufMiUnhL9w==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOXdVWGU2QXl6RTN3L3dk
            NWVmWktRUGNjMlE1blJPckcrazZxN05WeFQ0CjdjOUxtdGlNaHZpdXpwdE9lcC9U
            TkI0TGNyaWpsdTRQaXZ6d0hwcFc3L2cKLS0tIHdQNnh6Y2hsUWduUjV3T2hyd083
            OUYzTzlQYUpMVVAxeXFpbk1PbkJ2TVUK8s0WeUnhs818wrY4qJAZo1XFZfnCAjsF
            1aP4rIthPUAwjJaww38BS37QRv3JcMa68Kql35kQ0m2+VdOJSgB9pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T01:19:21Z"
    mac: ENC[AES256_GCM,data:AJOdRG6pn4d68YpKDUDdDi4EghNkNsl7sXTltq/OkWprkB4CWeJBSSs3F/gVjwRaWy4sCBxtAoLBVi5far3r7hCJ4A+NVpypURLmiKQQeZqAuZ11rMF67fs2yG8/VsCUyDpNG1V9oM+u1yApue9XdHVfRmX2sozSW8RDIDr1r7I=,iv:22k4++h8jh/mcs9nSOmRcS8Mk3n8xiw2QBXqrSqR86Y=,tag:TG3BlJr3tto8hEPFyWlIxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
