apiVersion: v1
kind: Secret
metadata:
    name: truenas-credentials
    namespace: flux-system
type: Opaque
stringData:
    TRUENAS_PASSWORD: ENC[AES256_GCM,data:2h8QY3HxhQLvAV0MrpIsQ3K9HA==,iv:lzFE11Yz9D05XHAB0DdAjSmHKFUsIa/EjWROYVYgV6g=,tag:W6rzV6enq1rfdxA8KbHOBw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:YaCqd6WbAlc0KKZnMbgjbvdIDBFAx2ok7mQW/UFUSvs1wvvsHNiTnw3a0CxBM0NniGy5rfvHpdoeci2tTqAeI8Hb,iv:OfWi7N7tNteXrjOLWX/MofYSunBtvcR0lrsXP5Fxpc8=,tag:6ULh3/J7li3GOrYM+mxH7A==,type:str]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeTdjY3hyOFpEYVQxVU9y
            TVFpRzF2ZXk2L2VubmtSYk54V3BFVUROY0JRCmJJdzEyZkk2K3dxeGVyYzNYb2tR
            aGswZmxoZUc2SmJtSTRUQUV5MXo3cVUKLS0tIHZCUktlWkRpeFo0ZHVnZE5hMDlJ
            SStGWE5pT2hMcTk5akNGS1VjSTBSbHcKd6FghuIeyU6mUhnFkuA65X8OVEGIoMiy
            a8z49Xj7baYjSyAhAMsDchmnMtpKls2nL4fRYPAGdvLEYvlYzlYaMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T01:11:36Z"
    mac: ENC[AES256_GCM,data:h2kfnjHfm60vND8H1gbEQbFSX8vJ9VXOO01OrY3qiQMDR0t1A4ht5ZXUjicf7GYo4nmyTbeS0yFrA+vlrrMzzvzanKL/mwjHOR+JtvB9SFQBX9/VhKG9ypTyQNlTyRrkmy1Ilv6kZ+i8bhT6wR7F7qcuTsLdY+DZMm1XF9l0pwE=,iv:9Vp4gSYe5MZVsy8485AM0NqMu1O+oPSK3bbyL+pmFns=,tag:/bsvnA8vkD4MsJaq8Vdczg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
