---
apiVersion: v1
kind: Namespace
metadata:
  name: onepassword
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 1h
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
      version: "2.0.5"
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  targetNamespace: onepassword
  values:
    connect:
      api:
        name: connect-api
        imageRepository: 1password/connect-api
        logLevel: info
        serviceMonitor:
          enabled: true
          interval: 30s
          path: "/metrics"
      credentialsName: onepassword-connect-secret
      credentialsKey: 1password-credentials.json
      tls:
        # Denotes whether the Connect API is secured with TLS
        enabled: false
        # The name of the secret containing the TLS key (tls.key) and certificate (tls.crt)
        secret: op-connect-tls
      nodeSelector:
        node: "worker"

    operator:
      # Denotes whether the 1Password Operator will be deployed
      create: true
      autoRestart: true
      pollingInterval: 600
      nodeSelector:
        node: "worker"
      # 1Password Operator Token Configuration
      token:
        # The name of Kubernetes Secret containing the 1Password Connect API token
        name: onepassword-token
        key: token
