---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app: "redis_cache_operations"
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: flux-system
spec:
  interval: 24h
  url: https://ot-container-kit.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-operator
      version: "0.22.2"
      sourceRef:
        kind: HelmRepository
        name: ot-helm
        namespace: flux-system
      interval: 6h
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: -1
  uninstall:
    keepHistory: false
  targetNamespace: redis
  values:
    redisOperator:
      name: redis-operator
      imageName: quay.io/opstree/redis-operator
      imageTag: "v0.22.1"
      imagePullPolicy: Always
      webhook: false
      automountServiceAccountToken: true
      metrics:
        enabled: true
        bindAddress: ":8080"
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    replicas: 1
    service:
      name: webhook-service
      namespace: redis
    certmanager:
      enabled: false
    manager:
      config:
        kubeClientTimeout: 60s
        kubeClientQPS: 0.0
