apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: it-tools
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  targetNamespace: it-tools
  values:
    controllers:
      it-tools:
        replicas: 1
        strategy: RollingUpdate
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/it-tools
              tag: 2024.10.22@sha256:4dfe650a4be1e13d59e37f2b2aa6b8faf915c8afb53a379ea5eaaba679a0a456
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    service:
      app:
        controller: it-tools
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: tailscale
        annotations:
        hosts:
          - host: it-tools
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: it-tools-tls
            hosts:
              - it-tools
    persistence:
      config:
        enabled: true
        storageClass: iscsi
        retain: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
