apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chart:
    spec:
      version: "1.9.1"
  values:
    defaultSettings:
      deletingConfirmationFlag: false
      snapshotMaxCount: 3
    longhornUI:
      replicas: 2
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      migratable: true
      nfsOptions: vers=4.2,noresvport,softerr,timeo=600,retrans=5
      reclaimPolicy: Retain
    preUpgradeChecker:
      jobEnabled: true
      upgradeVersionCheck: true
    service:
      manager:
        type: ClusterIP
        externalTrafficPolicy: Cluster
      ui:
        type: ClusterIP
        externalTrafficPolicy: Cluster
    metrics:
      serviceMonitor:
        enabled: false
    #defaultBackupStore:
   #   backupTargetCredentialSecret: aws-secret

